name: Build Docker Image
on: [push]

jobs:
  k8s:
    name: RemoteDockerImage
    runs-on: ubuntu-latest
    steps:
      - id: liftbridge
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            repository: liftbridge-io/liftbridge
      - id: checkout
        uses: actions/checkout@v2
        with:
            repository: liftbridge-io/liftbridge
            ref: ${{ steps.liftbridge.outputs.release }}
      - id: dockerfile
        run: |
            cp k8s/Dockerfile.k8s Dockerfile.k8s
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pozetroninc/liftbridge
          dockerfile: Dockerfile.k8s
          tags: latest, ${{ steps.liftbridge.outputs.release }}
          tag_with_ref: true
          tag_with_sha: true
